version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:3.141.59-xenon
    ports:
      - 4444:4444
      - 5900:5900
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./app/src"
        target: "/app"
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
    shm_size: "2gb"